<script>

	debugger;
	$(function() {
		$("button#generate").on("click", function() {
			debugger;
		});
	});

</script>

<div class="content">

    <label class="btn btn-default btn-file">
        Dossier vidéos
        <input type="file" directory mozdirectory webkitdirectory>
        <!-- <input type="file" accept="video/*" > -->
    </label>
    
    <button id='generate' type="button" class="btn btn-primary">Générer thumbnails</button>

</div>
