<?=
	$this->headLink()
    	->prependStylesheet($this->basePath('css/video-js.css'));
	
    $this->headScript()
    	->prependFile($this->basePath('js/videojs-ie8.min.js'))
    	->prependFile($this->basePath('js/video.js'));    
?>

<script>

	$(function() {
		$("button#generate").on("click", function() {
			debugger;
// 			var template = $('#video_template').html();
// 			$('#fileList').empty();
			
// 			var files = $('#files').prop("files");
// 			for (var i = 0; i < files.length; ++i) {
// 			    console.log(files[i]);
// 			    //Propriétés de la vidéo
// 			    var templateDOM = $.parseHTML(template)[0];
// 			    var source = $(templateDOM).find('source');
// 			    $(source).attr('src', files[i].name);
// 			    $(source).attr('type', files[i].type);

// 			    //Ajout DOM
// 			    $('#fileList').append(templateDOM);
// 			}
			$.ajax({
       			url : 'application/getFiles', // La ressource ciblée
       			type : 'GET', // Le type de la requête HTTP.
       			data : { dir: "John" },
       			success: function(data) {
           			debugger;
           			$("#fileList").html(data);
       			}
    		});
		});

		$("button#scan").on("click", function() {
			debugger;
			$.ajax({
       			url : 'application/scan', // La ressource ciblée
       			type : 'GET', // Le type de la requête HTTP.
       			data : { dir: "D:/NewsBin64/download/tmp" },
       			success: function(data) {
           			debugger;
           			$("#fileList").html(data);
       			}
    		});
		});
	});

</script>

<div class="content">

    <label class="btn btn-default btn-file">
        Dossier vidéos
        <input id="files" type="file">
        <!-- <input type="file" accept="video/*" > -->
    </label>
    
    <button id='generate' type="button" class="btn btn-primary">Générer thumbnails</button>
    <button id='scan' type="button" class="btn btn-primary">Scanner dossier</button>
    
    <video id="video_template" class="video-js vjs-default-skin" controls preload="none" width="640" height="264" poster="img/oceans.png" data-setup="{}">
    	<source src="" type="">
    	<p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
  	</video>
    
    <div id="fileList">
    </div>

</div>
